server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyhub?serverTimezone=Asia/Seoul
    username: root
    password: hanjea!1298
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false